// Generated by CoffeeScript 2.5.1
var jsd, random;

import {
  tree as setuList
} from './setuList.json';

random = function(min, max) {
  return parseInt(Math.random() * (max - min + 1) + min, 10);
};

jsd = 'https://cdn.jsdelivr.net/gh/laosepi/setu/pics/';

export default function(req, res) {
  var setuPath;
  setuPath = setuList[random(0, setuList.length)].path;
  return res.redirect(jsd + setuPath);
};
