// Generated by CoffeeScript 2.5.1
var jsd, random;

import sa from 'superagent';

import {
  tree as setuList
} from './setuList.json';

random = function(min, max) {
  return parseInt(Math.random() * (max - min + 1) + min, 10);
};

jsd = 'https://cdn.jsdelivr.net/gh/laosepi/setu/pics/';

export default async function(req, res) {
  var buffer, setuPath;
  setuPath = setuList[random(0, setuList.length)].path;
  buffer = ((await sa.get(jsd + setuPath))).body;
  res.setHeader('Content-Type', 'image/png');
  return res.send(buffer);
};
